# Generated by Django 5.1.7 on 2025-03-22 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the tutorial.', max_length=200, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(200)])),
                ('short_description', models.CharField(help_text='A short description of the tutorial (max 300 characters).', max_length=300, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(300)])),
                ('content', models.TextField(help_text='The main content of the tutorial.')),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image for the tutorial.', null=True, upload_to='tutorials/covers/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload a smaller thumbnail image for the tutorial.', null=True, upload_to='tutorials/thumbnails/')),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly slug for the tutorial.', max_length=200, unique=True)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO (max 300 characters).', max_length=300)),
                ('is_published', models.BooleanField(default=False, help_text='Is the tutorial published and visible to the public?')),
                ('is_featured', models.BooleanField(default=False, help_text='Should this tutorial be featured on the homepage?')),
                ('author_name', models.CharField(blank=True, help_text='The name of the author of the tutorial.', max_length=200)),
                ('author_bio', models.TextField(blank=True, help_text='A short bio of the author.')),
                ('author_image', models.ImageField(blank=True, help_text='Upload an image of the author.', null=True, upload_to='tutorials/authors/')),
                ('category', models.CharField(blank=True, help_text='The category of the tutorial.', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated list of tags for the tutorial.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, help_text='The date when the tutorial was published.', null=True)),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'ordering': ['-is_featured', '-published_date'],
            },
        ),
    ]
